Development
hoprnet/hopr-leaderboard pull request #23
Opened 2020-10-28 21:59 UTC by betinho89

The code base was improved, and the darkmode was enabled.

2020-10-29 09:55 UTC, nionis requested changes

2020-10-29 09:55 UTC, nionis commented on .gitignore
> +package-lock.json
why are we removing the `lock` files here?
It's considered best practise to include lock files, this ensures that people installing the repo will get precisely the same dependencies as you have.

2020-10-29 10:13 UTC, nionis commented
some feedback:

- `lock files`: https://github.com/hoprnet/hopr-leaderboard/pull/23#discussion_r514133154

- `copy to clipboard`: It doesn't always show the [tooltip](https://github.com/hoprnet/hopr-leaderboard/pull/23/files#diff-932eaa5789fa4d09a7b899a41bb4fe94bf524751aebb08dfc8a2b454bb02d7f8R26)

- some text is too dark, for example:
![image](https://user-images.githubusercontent.com/1877679/97553255-e5467980-19dd-11eb-9533-7cc31749d1ae.png)
let's make them "brighter"

- I see that we use 2 different highlight colors:
   1. `#2196f3` for the `dark mode toggle`
   2. `#FFC0CB` for icons, some numbers
let's switch into using `#2196f3` so it's more consistent

2020-10-29 15:43 UTC, jjperezaguinaga commented on .gitignore
> +package-lock.json
@nionis just as a background here, I think there was a confusion from https://github.com/hoprnet/hoprnet/pull/414 where I asked @betinho89 to remove `package-lock.json` and `yarn.lock` got included.

@betinho89 let's move `yarn.lock` outside of the `.gitignore`

2020-11-02 14:59 UTC, nionis commented
hey @betinho89, not sure if you are done & ready for review, but just in case I've got feedback for the latest commit: https://hopr-leaderboard-iklhzio5x.vercel.app/

- rename `copy to clipboard` to `copied to clipboard`
- `copy to clipboard` background color doesn't look very nice: maybe make the font color white? feel free to try out something
![copy](https://user-images.githubusercontent.com/1877679/97882222-08e62880-1d2c-11eb-9bdf-89987a044dfe.png)
- highlight colours still inconsistent, let's stick into using one, I prefer blue
![highlight](https://user-images.githubusercontent.com/1877679/97882327-2f0bc880-1d2c-11eb-9195-71097823764e.png)
- mouse hover on `id` column causes the horizontal scroll to popup on a `1920x1080` screen, it's fine if it does it for smaller screens `<720p`
![mouse_over](https://user-images.githubusercontent.com/1877679/97882487-56629580-1d2c-11eb-9d52-e579fc2ba9c6.png)
- make `id` column copy-able
- let's add to all copy-able texts the "copy" icon
- let's update [hopr-allocation](https://hopr-leaderboard-iklhzio5x.vercel.app/hopr-allocation) to https://github.com/hoprnet/hopr-leaderboard/issues/26

2020-11-09 09:12 UTC, nionis commented
@betinho89 is this PR ready for review?

2020-11-09 09:34 UTC, jjperezaguinaga commented
@nionis merging as its, and getting the fixes in a separate PR.

2020-11-09 09:34 UTC, merged